cncf/foundation

charter.md
12/10/18 - Formatting and numbering fixes
* Sections 5(e), 6(c)(iii)(c), 8 and 17 are affected by this change
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
=> Revision 8 - CNCF Charter - 12/10/18

code-of-conduct-languages/it.md
=> first commit

style-guide.md
it seems to have moved, found new one via Google search
=> fix link to IEEE Style Guide

copyright-notices.md
Signed-off-by: Steve Winslow <swinslow@gmail.com>
=> Add details on copyright notices

license-exceptions/README.md, license-exceptions/cncf-exceptions-2019-11-01.json, license-exceptions/cncf-exceptions-2019-11-01.spdx
Fixed #45 
Signed-off-by: Steve Winslow <swinslow@gmail.com>
=> Add granted license exceptions

travel_funding.md
PTAL @dankohn 
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
=> CNCF Scholarship / Travel Funding Process added

gb-developer-reps.md
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
Creating on behalf of CNCF staff to update the process for elections.
=> Maintainers Election Policy revised

webinar-guidelines.md
Add further definition on  member, project, ambassador, and SIG webinars
=> Update webinar guidelines

blog-guidelines.md
Adding blog types with definition.
Minor updates to text
=> Update blog guidelines

license-exceptions/README.md
breadcrumbs from https://github.com/cncf/foundation/issues/93
cc @caniszczyk
=> license-exceptions: update link to allowlist policy

code-of-conduct-languages/ko.md
Fix broken links at code-of-conduct-languages/ko.md
=> Fix broken links.

license-exceptions/cncf-exceptions-2019-11-01.json, license-exceptions/cncf-exceptions-2019-11-01.spdx
Followup to #93 and c9043bff -- this also updates the language in the lists of exceptions to be inclusive.
=> Update to inclusive language in exceptions files

code-of-conduct.md
Just a minor change in code-of-conduct.md. Fixing order of languages.
=> [Fix] Update code-of-conduct.md, sort language list (@kuritka)

agpl-recommendations.md
=> Add AGPL recommendations

conformance-programs.md
=> Add conformance program details

code-of-conduct-languages/tr.md
This is a document translation of the Code of Conduct that I translated to Turkish.
=> translation of code of conduct to turkish

project-maintainers.csv
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>
This PR adds Meshery maintainers to the list as mentioned in https://github.com/meshery/meshery/blob/master/MAINTAINERS.md
=> Update Meshery maintainers

charter.md
Adding for review - @taylorwaggoner
=> GB Chair election updates

project-maintainers.csv
Signed-off-by: GitHub <noreply@github.com>
=> docs: Update KEDA maintainers

project-maintainers.csv
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>
This PR updates the maintainers of SMP and the Meshery projects.
=> update Meshery and SMP maintainers

project-maintainers.csv
cc: @sclevine , @nebhale, @hone, @jkutner  who were on the existing maintianers list.
=> Update Buildpacks maintainers list

project-maintainers.csv
I stepped down as tinkerbell maintainer a few weeks ago
https://github.com/tinkerbell/.github/pull/31
=> EMERITUS tinkerbell maintainer

project-maintainers.csv
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>
=> project-maintainers.csv: Update KubeVirt maintainers

project-maintainers.csv
=> Update maintainers for Pixie

project-maintainers.csv
Signed-off-by: Chris Wayne <cwayne18@gmail.com>
Update k3s maintainers and fix typo in github name
=> Update k3s maintainers

project-maintainers.csv
Signed-off-by: Alkin Tezuysal <alkin.tezuysal@gmail.com>
=> Add Manan Gupta(GuptaManan100) as Vitess project maintainer

license-notices.md
Fixes #189 
cc @caniszczyk, @amye  
=> Add recommendations for license notices in files

project-maintainers.csv
Add @skoech as a maintainer to the Tremor project
=> Add new tremor maintainer skoech

project-maintainers.csv
Signed-off-by: Shirong Hao <shirong@linux.alibaba.com>
=> Add Inclavare Containers as Sandbox

project-maintainers.csv
Signed-off-by: Timofey Ilinykh <timofey.ilinykh@absa.africa>
=> Update k8gb maintainers list

project-maintainers.csv
This PR updates the roster of org-level Brigade maintainers.
=> update brigade maintainers

project-maintainers.csv
This updates the Harbor maintainers list to match https://github.com/goharbor/community/blob/master/MAINTAINERS.md
cc @reasonerjt @kofj @danielpacak @mmpei @renmaosheng @wy65701436 @ywk253100 @hainingzhang @steven-zou @jMonsinjon @holyhope @xaleeks @tianon @Vad1mo
=> Update Harbor project maintainers

project-maintainers.csv
Update the list with two newly added etcd maintainers.
=> Update etcd maintainers

project-maintainers.csv
@amye I've manually updated the CSV to match our MAINTAINERS.md per your email.
=> Update OPA maintainers

project-maintainers.csv
Update the list to add and remove Helm maintainers.
=> Update Helm maintainers

project-maintainers.csv
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
=> Change jpkrohling's affiliation

project-maintainers.csv
Hey @amye 
I have just found a typo in my name, and this PR fixes it.
Thank you :pray:
=> fix(project-maintainers.csv): correct a typo in my name

project-maintainers.csv
Company affiliation has changed.
=> Update Vitess maintainer rafael

project-maintainers.csv
@open-telemetry/governance-committee
=> Update OpenTelemetry GC members

project-maintainers.csv
Signed-off-by: André Martins <andre@cilium.io>
=> Add Cilium project maintainers

project-maintainers.csv
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
=> Sync up the latest Fluentd maintainers list

project-maintainers.csv
Signed-off-by: austin <austin@redhat.com>
=> Remove inactive maintainers for Operator SDK

project-maintainers.csv
part of:
- https://github.com/cncf/toc/issues/753
=> Add K8up project maintainers

project-maintainers.csv
Welcome @JorTurFer as a new KEDA maintainer!
Relates to kedacore/governance#38
=> chore: Welcome Jorge Turrado Ferrero as a new KEDA maintainer!

project-maintainers.csv
Ref: cncf/toc#752
Signed-off-by: Rahul Jadhav r@accuknox.com
=> Add Kubearmor maintainer list

project-maintainers.csv
For https://github.com/cncf/toc/issues/754 via https://github.com/kube-rs/.github/blob/main/maintainers.md
=> Add kube-rs maintainers

project-maintainers.csv
Please take a look if your information is correct @Nexucis, @mxinden, @kakkoyun, @squat, @onprem, @yeya24.
Updates taken from the projects maintainer lists.
=> Update Thanos maintainers and add new Prometheus maintainers too

project-maintainers.csv
Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>
=> Fix typo: Keda -> KEDA

project-maintainers.csv
Adding the names of new companies for two members
=> Updates to Dapr Maintainers list

project-maintainers.csv
- Updated OpenGitOps maintainers file location
- Added @chris-short
- Updated @murillodigital affiliation
=> Update OpenGitOps maintainers people and file location

project-maintainers.csv
Signed-off-by: Alvin Lin <alvinlin123@gmail.com>
=> Add alanprot to Cortex maintainer list

blog-guidelines.md
=> blog promotion updates

case-study-guidelines.md
=> fix case-studies link

project-maintainers.csv
Related to https://github.com/cncf/toc/issues/773
=> Add Devfile maintainers

project-maintainers.csv
Taking Tarun off the list and adding Matei David
=> Updating Linkerd maintainer

project-maintainers.csv
Adding @miaida missing GH username in project-maintainers.csv
=> Add devfile maintainer Ida Olsen GH username

project-maintainers.csv
add a new maintainer to the maintainer list for OpenELB
=> add a new maintainer to the maintainer list for OpenELB

project-maintainers.csv
(this makes it match our MAINTAINERS File
=> project-maintainers: in-toto: add new maintainers

project-maintainers.csv
Updates the Open Service Mesh maintainers
as per https://github.com/openservicemesh/osm/blob/main/OWNERS.
=> Update Open Service Mesh maintainers

project-maintainers.csv
add knative project
Related to [INCUBATING PROJECT ONBOARDING] Knative https://github.com/cncf/toc/issues/794
Related to https://github.com/knative/community/issues/945
=> add knative project

project-maintainers.csv
* Replaces @APTy with @MarcosDY
* Corrects the name and company affiliation of @amartinezfayo
=> Update SPIRE maintainers

project-maintainers.csv
Signed-off-by: genghaotao <genghaotao@beyondcent.com>
=> add maintainers of FabEdge project for onboarding

project-maintainers.csv
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
=> Update Notary Project maintainers

charter.md
Fixes possible omission on line 59 to include gold members (lines 71..75)
=> Include Gold in list of members

project-maintainers.csv
- Add Paulo Gomes
- Fix maintainers yaml
=> Update Flux maintainers

project-maintainers.csv
Ref: https://github.com/vitessio/vitess/pull/10072
=> Add Matt Lord to Vitess maintainers

project-maintainers.csv
- Add Hasan Turken (@turkenh)
Signed-off-by: Hasan Turken <turkenh@gmail.com>
=> Update Crossplane maintainers

project-maintainers.csv
Hooray!
Signed-off-by: Andrew Burden <aburden@redhat.com>
=> KubeVirt to Incubating

project-maintainers.csv
https://github.com/cncf/toc/issues/831
=> add sealer maintainers

project-maintainers.csv
add OpenFunction maintainers, for [cncf/toc#829](https://github.com/cncf/toc/issues/829)
Signed-off-by: laminar <fangtian@kubesphere.io>
=> add OpenFunction maintainers

project-maintainers.csv
https://github.com/cortexproject/cortex/pull/4730
=> Add Friedrich Gonzalez to Cortex maintainer

project-maintainers.csv
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
=> Changes to Prometheus maintainers

project-maintainers.csv
Signed-off-by: zhaohuabing <zhaohuabing@gmail.com>
=> Add Aeraki Mesh maintainers

code-of-conduct.md
Changes requested by the Interim CNCF Code of Conduct Committee (COCC)
=> Update coc with changes from interim cocc

code-of-conduct.md
Minor updates from the Interim Code of Conduct Committee that didn't get included Jeefy's PR from yesterday (which has already been merged)
Signed-off-by: Joanna Lee <52938823+joannalee339@users.noreply.github.com>
=> Minor updates to Code of Conduct from Interim CoC Committee

project-maintainers.csv
We archived fluxcd/webui
- fluxcd/webui#65
- fluxcd/community#215
- fluxcd/community#216
In addition to that Max updates his affilation: fluxcd/community#217
=> Flux maintainers updates

project-maintainers.csv
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
=> Welcome Josh Abreu to the Prometheus Team

project-maintainers.csv
Signed-off-by: Ginger Collison <ginger@synadia.com>
Adding [Tomasz Pietrek](https://github.com/jarema)
=> Update project maintainers NATS

project-maintainers.csv
Signed-off-by: zhaohuabing <zhaohuabing@gmail.com>
=> update aeraki mesh maintainer

project-maintainers.csv
Add new Emissary maintainer [Lance Austin](@lanceea)!
Signed-off-by: Flynn <emissary@flynn.kodachi.com>
=> Add new Emissary maintainer Lance Austin!

project-maintainers.csv
Signed-off-by: oilbeater <liumengxinfly@gmail.com>
=> Add new Kube-OVN maintainers

project-maintainers.csv
Add eso maintainers as per https://github.com/cncf/toc/issues/882 and https://github.com/external-secrets/external-secrets/issues/1395
=> add eso maintainers

project-maintainers.csv
Copy pasted and missed Gustavo's company in the file. Also I think the extra comma in line 1078 broke pre-vizualization in github
=> fix Gustavo's company and fix csv columns

project-maintainers.csv
This is so I can file tickets on behalf of other maintainers.
=> Add myself as a maintainer of cloud custodian

project-maintainers.csv
Sara has stepped down as a maintainer.
See https://github.com/vitessio/vitess/pull/10625
=> Vitess: remove Sara from maintainers

project-maintainers.csv
Add myself to the Jetstack cert-manager team
=> Add myself to the Jetstack cert-manager team

project-maintainers.csv
Adding Konveyor Maintainers as per https://github.com/cncf/toc/issues/880
=> add Konveyor Maintainers

project-maintainers.csv
PR as a basis for update https://github.com/etcd-io/etcd/pull/14373
=> Update list of etcd maintainers

project-maintainers.csv
Add Serverless Devs Project
> For : https://github.com/cncf/toc/issues/919    
> Create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it
=> add Serverless Devs

project-maintainers.csv
Lima was approved as a CNCF Sandbox project recently
- https://github.com/cncf/toc/issues/924
cc @jandubois
=> Add Lima maintainers

project-maintainers.csv
=> Adding ContainerSSH maintainers

project-maintainers.csv
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
xref https://github.com/knative/community/pull/1168
=> Update knative maintainers

project-maintainers.csv
Adding Kubewarden and its maintainers to the list of project maintainers.
=> Add Kubewarden project and maintainers

project-maintainers.csv
Adding @hemanthmalla 
Signed-off-by: Liz Rice <liz@lizrice.com>
=> Add Hemanth Malla to Cilium maintainers

project-maintainers.csv
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
=> Add Bryan Boreham to Prometheus team

README.md
Mailing list changes can be requested by email, but I wasn't sure we want to publish the address? 
Signed-off-by: Liz Rice <liz@lizrice.com>
=> Document how to update project maintainers

project-maintainers.csv
Signed-off-by: Jianbo Sun <jianbo.sjb@alibaba-inc.com>
=> update maintainer list of kubevela

project-maintainers.csv
Signed-off-by: Kevin Hannon <kannon1992@gmail.com>
=> adding armada maintainers

project-maintainers.csv
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
=> Switch dims employer to aws

project-maintainers.csv
Signed-off-by: Alvin Lin <alvinlin123@gmail.com>
=> Update maintainer list for Cortex project

project-maintainers.csv
=> update Michael's affiliation

project-maintainers.csv
Signed-off-by: Thomas Schuetz <38893055+thschue@users.noreply.github.com>
=> Update Incubating Status and Maintainer List for Keptn

project-maintainers.csv
In accordance with https://github.com/cilium/cilium/pull/22204 add @xmulligan to Cilium maintainers
Signed-off-by: Liz Rice <liz@lizrice.com>
=> Add Bill Mulligan to Cilium maintainers

project-maintainers.csv
Signed-off-by: Nick Young <nick@isovalent.com>
=> Remove youngnick as Contour maintainer

project-maintainers.csv
ref: https://github.com/kubernetes/steering/issues/260
Signed-off-by: Stephen Augustus <foo@auggie.dev>
cc: @amye @caniszczyk
cc: @parispittman @cpanato @mrbobbytables @cblecker
=> maintainers/kubernetes: Paris to Emeritus, add Carlos

project-maintainers.csv
Ref: https://github.com/vitessio/vitess/pull/11865
Also fixed company affiliations that have changed.
=> Add Frances Thai to Vitess maintainers

project-maintainers.csv
Related to https://github.com/knative/community/pull/1228
New members established here https://github.com/knative/community/blob/main/peribolos/knative-OWNERS_ALIASES#L192
=> update knative roster

project-maintainers.csv
Signed-off-by: salaboy <Salaboy@gmail.com>
=> Updating @salaboy company affiliation

project-maintainers.csv
Signed-off-by: hwdef <hwdefcom@outlook.com>
Ref: https://github.com/cncf/toc/issues/974
=> add carina maintainers

project-maintainers.csv
Signed-off-by: Atulpriya Sharma <sharma.atulpriya@gmail.com>
Adding Paralus maintainers.
Ref: https://github.com/cncf/toc/issues/973
=> Adding Paralus Maintainers

project-maintainers.csv
Signed-off-by: Omri Gazitt <ogazitt@gmail.com>
=> Add OPCR to project-maintainers

project-maintainers.csv
Signed-off-by: Jason Hall <jason@chainguard.dev>
=> Add ko maintainers

project-maintainers.csv
Signed-off-by: Alexey Igrychev <alexey.igrychev@flant.com>
=> Add werf maintainers

project-maintainers.csv
Added full maintainer list to OPCR maintainers
Signed-off-by: Omri Gazitt <ogazitt@gmail.com>
=> Added OPCR maintainers

project-maintainers.csv
To better reflect the current state of the project
Signed-off-by: Peter Hunt <pehunt@redhat.com>
=> project-maintainers.csv: update CRI-O maintainers

project-maintainers.csv
Please see https://github.com/fluent/fluentd/blob/master/MAINTAINERS.md
=> Add toru-takahashi to Fluentd maintainers

project-maintainers.csv
- https://github.com/lima-vm/lima/pull/1323
@afbjorklund @balajiv113 PTAL
=> project-maintainers.csv: update Lima maintainers

project-maintainers.csv
Update Telepresence maintainers.
Signed-off-by: Ana Filipa de Almeida <anafilipadealmeida@gmail.com>
=> project-maintainers.csv: update Telepresence maintainers

project-maintainers.csv
See https://github.com/cilium/cilium/pull/23344
=> Add Casey Callendrello to Cilium maintainers

project-maintainers.csv
See https://github.com/falcosecurity/evolution/blob/main/MAINTAINERS.md#core-maintainers
Thank you, Melissa
=> Add Melissa Kilby (incertum) to Falco maintainers

project-maintainers.csv
=> Revert "project-maintainers.csv: update Telepresence maintainers"

project-maintainers.csv
https://github.com/kubecost/opencost/blob/develop/MAINTAINERS.md 
I'm Kubecost's community manager for OpenCost.
=> Add Matt Ray to OpenCost maintainers

project-maintainers.csv
=> Update bwplotka affinity.

project-maintainers.csv
=> Update my affiliation

project-maintainers.csv
Changing the company for Colin Sullivan from 'Synadia' to 'Luxant Solutions'. There is no space for the new email 'colin@luxantsolutions.com'
=> Updating NATS Maintainer list

project-maintainers.csv
Ref: https://github.com/vitessio/vitess/pull/12329
=> Vitess: add dbussink to maintainers

project-maintainers.csv
=> Update affiliation of @oleg-nenashev in Keptn

project-maintainers.csv
Updated the typo and wrong URL link.
=> Update etcd maintainer's info

project-maintainers.csv
Sorry, misspelled my own github id
=> Fix ORAS maintainers

project-maintainers.csv
https://github.com/cilium/cilium/pull/24864
=> add Lorenz Bauer to Cilium Maintainers

project-maintainers.csv
Please see https://github.com/fluent/fluentd/blob/master/MAINTAINERS.md
Recently we elected @daipom as a new maintainer at https://github.com/fluent/fluentd/pull/4069.
=> Add daipom to Fluentd maintainers

project-maintainers.csv
ref: https://github.com/kubearmor/KubeArmor/blob/main/MAINTAINERS.md
=> update KubeArmor maintainer's list

project-maintainers.csv
Reverts cncf/foundation#564 - it still needs affiliations!
=> Revert "Add Headlamp maintainers"

project-maintainers.csv
Update the repo link and maintainers
=> Update project-maintainers.csv for skooner/k8dash

project-maintainers.csv
Adding Inspektor Gadget maintainers entry for new Sandbox project as per https://github.com/cncf/toc/issues/1021
=> Add Inspektor Gadget maintainers

project-maintainers.csv
Adding Headlamp maintainers entry for new Sandbox project as per https://github.com/cncf/toc/issues/1056
=> Add Headlamp maintainers

project-maintainers.csv
https://github.com/clusterpedia-io/clusterpedia/blob/main/MAINTAINERS.md
Yingjun Wu's email: wuyingjun@cmss.chinamobile.com
=> Add Yingjun Wu to Clusterpedia Maintainers

project-maintainers.csv
For cncf/toc#1094
Maintainer emails:
| Maintainer    | GitHub ID      | Scope     | Email                       |
| ------------- | -------------- | --------- | --------------------------- |
| Liang Sun     | @sun7927       | Owner     |  <liang.sun@daocloud.io>     |
| Kay Yan       | @yankay        | Dev       | <kay.yan@daocloud.io>       |
| MingMing Zhou | @SSmallMonster | Dev       |  <mingming.zhou@daocloud.io> |
| buffalo1024   | @buffalo1024   | Dev       |  <kaichen.yi@daocloud.io>    |
| A_tian        | @FloatXD       | Test      |  <1416297674@qq.com>         |
| EchoS         | @zhaosimon     | Community | <simon.zhao@daocloud.io>    |
| Michael Yao   | @windsonsea    | Docs      | <haifeng.yao@daocloud.io>   |
=> Add HwameiStor maintainers

project-maintainers.csv
Hi! 👋 I would like to update my employer info. Thank you! :)
=> Update Niki Manoledaki's company

project-maintainers.csv
xref: https://github.com/cncf/toc/issues/1057
xref: https://github.com/getsops/community/issues/4
=> Add SOPS maintainers

project-maintainers.csv
doc. update CubeFS maintainers
=> doc. update CubeFS maintainers

project-maintainers.csv
Ref: https://github.com/cilium/cilium/pull/26603
=> Add Jussi Mäki as a Cilium project maintainer

project-maintainers.csv
Eraser is a new sandbox project. This PR adds all maintainers.
=> added Eraser maintainers

project-maintainers.csv
https://groups.google.com/g/prometheus-developers/c/73twl6CPE0Q
=> Add new Prometheus maintainers

.gitignore, code-of-conduct/coc-committee-charter.md, code-of-conduct/coc-committee-jurisdiction-policy.md, code-of-conduct/coc-incident-resolution-procedures.md
* Charter
* Jurisdiction policy
* Resolution procedures
=> Adding approved Code of Conduct Committee changes

project-maintainers.csv
https://github.com/kubevela/community/pull/182
=> Update KubeVela maintainer

project-maintainers.csv
As the CODEOWNERS files shows, we are not active maintainers anymore.
cc @johananl
=> Remove myself and Johannes as metallb maintainers

project-maintainers.csv
- updated project status to Graduated
- fixed link to maintainers page
- fixed company affiliations for maintainers
=> Update entry for KEDA

project-maintainers.csv
Adding maintainers for new sandbox project [Copa](https://github.com/cncf/toc/issues/1170?utm_source=pocket_saves)
=> docs: add copa and maintainers

project-maintainers.csv
Added new maintainer for PipeCD
https://github.com/pipe-cd/pipecd/pull/4607
=> Add new PipeCD maintainer

project-maintainers.csv
Removed maintainer and added another. 
https://github.com/orgs/jaegertracing/teams/jaeger-maintainers
=> Fixing Jaeger Maintainers

project-maintainers.csv
For reference you can check that I'm listed as a team member/maintainer here https://prometheus.io/governance/#team-members
@taylorwaggoner reached out to me to ask me to add myself to the list to make things consistent.
=> Update Prometheus maintainers including Jesús Vázquez

project-maintainers.csv
Thanks to Liz Rice for observing this was out of date :-)
=> Update affiliation for Casey Callendrello

project-maintainers.csv
=> fix csv format issue by removing an extra ,

project-maintainers.csv
This PR updates Andrea Terzolo's affiliation in the `project-maintainers.csv` file
=> Update project-maintainers.csv 

project-maintainers.csv
=> correcting formatting in project-maintainers.csv

project-maintainers.csv
Adding @christianh814 to Argo Project maintainers list.
https://github.com/argoproj/argoproj/blob/main/MAINTAINERS.md?plain=1#L34
=> Add christianh814 to Argo Project maintainers list

project-maintainers.csv
Adding myself and my colleague:
https://github.com/argoproj/argoproj/blob/54f8bb1c5c7eba6455f6d4414ef67bdb8cbc2bb3/MAINTAINERS.md?plain=1#L23
https://github.com/argoproj/argoproj/blob/54f8bb1c5c7eba6455f6d4414ef67bdb8cbc2bb3/MAINTAINERS.md?plain=1#L51
=> Add Joibel and isubasinghe to argo maintainers

project-maintainers.csv
Updating Dapr maintainers as of March 19th 2024.
=> Updating Dapr maintainers as of March 19th 2024.

project-maintainers.csv
Updating my affiliation in the project-maintainers list.
=> Update joshuagl's affiliation

project-maintainers.csv
https://github.com/envoyproxy/gateway/blob/f8a8c0bd3d8c3e28a203bd406848e279840a128e/OWNERS#L18
=> Add guydc as envoy gateway maintainer

charter.md
Per the [final doc](https://docs.google.com/document/d/1HHy3KJQD9rVvE-URg_DzCORRB9JM-OnPfxt9WqOvk-4/edit), updating the charter with the values voted on in the 02/26/2024 GB meeting
cc @caniszczyk @thefoxatwork
=> Update charter with values, voted on 20240226

project-maintainers.csv
=> Make the file beautiful and searchable

project-maintainers.csv
See https://github.com/vitessio/vitess/pull/15495 and vitessio/vitess#15733
=> vitess: update affiliation for Andrew Mason, remove Dan Kozlowski

project-maintainers.csv
as HwameiStor & SpiderPool maintainer
=> add panpan0000

project-maintainers.csv
Remove 3 people, add 1 new person.
=> update OpenELB maintainers list

project-maintainers.csv
=> Update OpenFeature maintainers list

project-maintainers.csv
relates to https://github.com/cncf/toc/issues/1300
=> Add Kairos maintainers

project-maintainers.csv
for https://github.com/cncf/toc/issues/1298
=> Add maintainers for KubeSlice

project-maintainers.csv
This PR adds myself to the Vitess maintainers, also it fixes an extra whitespace character in the previous maintainer's entry
cc @deepthi for review/approval
=> Add timvaillancourt to Vitess maintainers

project-maintainers.csv
CE is now Graduated (and update Doug's affiliation)
=> Update CloudEvents status

project-maintainers.csv
This PR is for [cncf/toc#1302](https://github.com/cncf/toc/issues/1302)
=> Add maintainers for Koordinator

project-maintainers.csv
Ref: https://github.com/konveyor/community/blob/main/MAINTAINERS.md
=> Add Dylan Murray as Konveyor Maintainer

project-maintainers.csv
Add initial set of maintainers for [Radius](radapp.io) as a part of https://github.com/cncf/toc/issues/1303
=> add radius maintainers

project-maintainers.csv
Adding new maintainers to Kepler sandboxing project
=> Update Kepler maintainers

project-maintainers.csv
=> Add David Ashpole as Prometheus team member

project-maintainers.csv
I was elected to the SPIFFE/SPIRE SSC.
=> Add kfox1111

project-maintainers.csv
Ref:
- Curiefense: https://github.com/cncf/toc/issues/1192
- OpenEBS: https://github.com/cncf/toc/issues/1051
- Krator: https://github.com/cncf/toc/issues/1252
- Fonio: https://github.com/cncf/toc/issues/1199
- OpenMetrics: https://github.com/cncf/toc/issues/1242
=> Removes archived project maintainers

project-maintainers.csv
See https://github.com/cortexproject/cortex/pull/6032
=> Include new maintainer Cortex and update my handle

project-maintainers.csv
- https://github.com/cncf/toc/issues/1369
=> feat(project-maintainers): add atlantis project maintainers

project-maintainers.csv
https://github.com/kedacore/governance/issues/108
=> chore: Ahmes ElSayed is stepping down

blog-guidelines.md
=> Update blog-guidelines.md - SIGs to TAGs

project-maintainers.csv
Hi,
Please review and accept the enclosed adds to the list of openGemini maintainers.
Thanks!
=> docs: add openGemini maintainers

cncf-membership-guide.md
This PR introduces a comprehensive CNCF Membership Engagement Guide to the foundation repository. The guide is designed to help CNCF member organizations maximize the value of their membership and increase their engagement with the cloud native ecosystem.
- Detailed strategies for leveraging CNCF membership benefits
- Step-by-step guidance on establishing internal CNCF engagement teams
- Tips for enhancing visibility, contributing to open source, and participating in CNCF governance
- Resources for training, certification, and continued learning
The purpose of this guide is to:
1. Provide a clear roadmap for new and existing CNCF members to utilize their membership fully
2. Encourage active participation in the CNCF community
3. Help members align their organizational goals with CNCF …
=> Add CNCF Membership Engagement Guide

code-of-conduct-languages/hu.md, code-of-conduct.md
- This PR adds Hungarian translated code-of-conduct
=> docs: add hungarian code-of-conduct

project-maintainers.csv
As reqested in https://github.com/cncf/toc/issues/1375
=> Add bpfman maintainers

source-available-recommendations.md
=> Add expanded source available recommendations

project-maintainers.csv
I recently became a Falco maintainer and I'm now adding myself to `project-maintainers.csv`
=> update(project-maintainers.csv): add loresuso as Falco maintainer

project-maintainers.csv
Hynek is stepping down as a maintainer of Keycloak; https://github.com/keycloak/keycloak/pull/31798
=> Update project-maintainers.csv for Keycloak

proprietary-interactions-guidance.md
=> Add guidance on interactions with proprietary products

project-maintainers.csv
HAMi already accept into the sandbox by TOC Voted
https://github.com/cncf/toc/issues/1413
=> add HAMi maintainers

project-maintainers.csv
Add [maryamtahhan](https://github.com/maryamtahhan) to Kepler's maintainers list
=> Update Kepler's maintainers list

project-maintainers.csv
This PR is related to LoxiLB's CNCF Sandbox Onboarding - https://github.com/cncf/toc/issues/1409
=> Add loxilb maintainers in project-maintainers.csv

project-maintainers.csv
And unfortunately remove Tom :(
Relates: https://github.com/kedacore/governance/issues/114
=> Welcome Jan Wozniak as a new KEDA maintainer!

project-maintainers.csv
- add new maintainers
- update affiliation of existing maintainers
cc @nyrahul  @daemon1024 @rksharma95
=> Update KubeArmor maintainers

project-maintainers.csv
Related to https://github.com/cncf/sandbox/issues/131
Add Project Shipwright maintainers.
=> Add Project Shipwright maintainers

project-maintainers.csv
Update my affiliation following my change of employer.
=> Update affiliation for Cilium maintainer

project-maintainers.csv
Part of [KusionStack Sandbox Onboarding](https://github.com/cncf/sandbox/issues/295).
=> Add KusionStack maintainers

project-maintainers.csv
My username was changed from @samj1912 to @sambhav. Make an update.
=> Update github username

project-maintainers.csv
@dlapcevic recently joined the Cilium maintainers [1].
1 - https://github.com/cilium/cilium/pull/35357
=> Add Dorde as Cilium maintainer

project-maintainers.csv
See https://github.com/dapr/community/issues/553
=> Add Whit Waldo as Dapr maintainer

project-maintainers.csv
Adding OpenEBS maintainers to project-maintainers.csv.
=> chore: adding OpenEBS maintainers

project-maintainers.csv
Hi,
Please review and accept the enclosed updates to the list of Meshery maintainers.
Thanks!
cc: @leecalcote
=> Update project-maintiners.csv: Meshery

project-maintainers.csv
Part of Sandbox checklist: https://github.com/cncf/sandbox/issues/302#issuecomment-2428533428
=> Add OVN-Kubernetes maintainers

project-maintainers.csv
Included KAITO maintainers list, following the [onboarding checklist](https://github.com/cncf/sandbox/issues/298) for KAITO
=> Signed-off-by: Sachi Desai <desaisachi345@gmail.com>

project-maintainers.csv
Update github ID.
The previous PR https://github.com/cncf/foundation/pull/779
=> Update Kubean maintainer

project-maintainers.csv
Dapr graduated recently. I simply updated the maintainer list to reflect this.
=> Updated maintainer list to reflect Dapr graduation

project-maintainers.csv
https://github.com/cortexproject/cortex/pull/6076
=> Update new maintainer Cortex (danielblando)

project-maintainers.csv
Hi,
Please review and accept the enclosed updates to the list of Meshery maintainers.
Thanks!
cc @leecalcote
=> Update project-maintainers.csv: Meshery

project-maintainers.csv
Base：
https://github.com/argoproj/argoproj/blob/2db4cda94956307ee080f51759aa6fcbda841f28/MAINTAINERS.md?plain=1#L53
Thanks！
=> Add shuangkun to Argo Maintainers

project-maintainers.csv
cert-manager is now a Graduated project. 🎉 Also some other minor project updates while on it.
=> Update cert-manager with current project status

project-maintainers.csv
We had some changes in the maintainers of k8up, this change reflects the current state.
=> Update maintainers of K8up

project-maintainers.csv
cc @mahadzaryab1
Also fix
* link to Maintainers doc
* Albert's affiliation
=> Add mahadzaryab1 as Jaeger maintainer

code-of-conduct-languages/fa.md
In part of this text, words are stuck together, making it unreadable in Farsi/Persian.
=> Improved Farsi Formatting

project-maintainers.csv
We had some changes in the maintainers of spiderpool, this change reflects the current state
=> update project maintainers for spiderpool

project-maintainers.csv
Hi there! This is an update to the Tinkerbell maintainers list. Thanks!
Corresponding changes were made in the project. https://github.com/tinkerbell/org/blob/main/ADMINS.md
I have also sent an email to cncf-maintainer-changes@cncf.io
=> Update Tinkerbell project maintainers

project-maintainers.csv
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
=> Change affiliation - jpkrohling

project-maintainers.csv
- Update KubeEdge to Graduated project.
- Update KubeEdge maintainers according to: https://github.com/kubeedge/kubeedge/blob/master/MAINTAINERS.md#technical-steering-committee
=> Update kubeedge maintainer

cncfgroups.md
=> Fixing typo on cncfgroups.md

project-maintainers.csv
_If you're adding a new maintainer to the CSV file, please confirm each of these actions has been completed:_
=> Update affiliation of @oleg-nenashev

project-maintainers.csv
Adding Kirtana Ashkok to maintainer list
=> Update project-maintainers.csv Kirtana added to containerd maintainers

project-maintainers.csv
see https://github.com/cilium/cilium/pull/37717
=> Add Marco as Cilium Maintainer

project-maintainers.csv
=> update: change Gergely Brautigam, skarlso, company affiliation

project-maintainers.csv
=> Update k8gb maintainers

project-maintainers.csv
=> add sandbox slimfaas maintainers

project-maintainers.csv
=> Add Sandbox Drasi Maintainers to projectmaintainers.md

project-maintainers.csv
part of the onboarding checklist: https://github.com/cncf/sandbox/issues/134
=> add Perses owners

project-maintainers.csv
=> update opencost maintainers

project-maintainers.csv
=> chore: update Open Cluster Management maintainers list

project-maintainers.csv
=> Update Kured entry

project-maintainers.csv
Reflecting recent changes in the project
=> Remove jmacd from OpenTelemetry TC

.github/ISSUE_TEMPLATE/license-exception-request.yaml
Update template according to @swinslow's suggested changes. This version asks questions up front that often been asked as follow up questions during the review process. 
Preview is available here: https://github.com/krook/issue-template-testing/issues/new?template=issue-template.yaml
=> Updated license exception request template.

website-guidelines.md
Follow up to https://github.com/cncf/foundation/pull/970 based on https://github.com/cncf/techdocs/pull/298#discussion_r1985172785
=> updating formatting of copyright guidelines

project-maintainers.csv
As part of https://github.com/cncf/sandbox/issues/351
=> Add Cozystack Maintainers

project-maintainers.csv
Update a karmada maintainer's company affiliations. Thank you.
Ref: https://github.com/karmada-io/community/issues/119
=> Update Karmada maintainers company

project-maintainers.csv
This PR updates the Metal3.io project maintainers list.
=> Update Metal3.io project maintainers list

project-maintainers.csv
FYI https://github.com/argoproj/argoproj/pull/359
=> chore: add name under Argo CD maintainers list

project-maintainers.csv
In support of https://github.com/cncf/sandbox/issues/333
=> Add k0s maintainers

project-maintainers.csv
=> Add KubeFleet owners

project-maintainers.csv
=> Updated OpenFGA Maintainers

project-maintainers.csv
Update the list according to pipe-cd/pipecd#5711
=> Update PipeCD maintainers

project-maintainers.csv
This is a part of https://github.com/cncf/sandbox/issues/332
=> Add container2wasm maintainer

project-maintainers.csv
=> Updating kube-burner maintainers

project-maintainers.csv
=> Add varodrig - julius - franciscojavierarceo to Kubeflow Maintainers

project-maintainers.csv
This is a part of https://github.com/cncf/sandbox/issues/297#issuecomment-2435499124
=> Add youki maintainer

project-maintainers.csv
@MikeZappa87 @bleggett @mlguerrero12 @dougbtv
https://github.com/containernetworking/cni/pull/1154
https://github.com/containernetworking/cni/pull/1157
cc: @s1061123 @squeed
=> Update CNI Maintainers

project-maintainers.csv
See source in https://github.com/bootc-dev/bootc/blob/main/MAINTAINERS.md
=> project-maintainers: Add bootc

project-maintainers.csv
=> Add KitOps project maintainers

project-maintainers.csv
=> Update KubeVirt Maintainers

project-maintainers.csv
=> Update openGemini maintainers info

project-maintainers.csv
=> add ibakshay as Perses maintainer

project-maintainers.csv
See https://github.com/cilium/cilium/pull/39625
=> Add Fabio Falzoi as Cilium Maintainer

project-maintainers.csv
=> Update Kyverno maintainers

project-maintainers.csv
=> envoy: update envoy maintainers

project-maintainers.csv
Dapr issue: https://github.com/dapr/community/issues/608
=> Add Artur Ciocanu as Dapr maintainer

project-maintainers.csv
Remove archived projects:
* [Krustlet](https://github.com/cncf/toc/issues/1385)
* [Curve](https://github.com/cncf/toc/issues/1479)
* [FabEdge](https://github.com/cncf/toc/issues/1478)
* [Nocalhost](https://github.com/cncf/toc/issues/1569)
* [superedge](https://github.com/cncf/toc/issues/1570)
* [KubeDL](https://github.com/cncf/toc/issues/1571)
* [Sealer](https://github.com/cncf/toc/issues/1525)
* [Teller](https://github.com/cncf/toc/issues/1544)
* [Merbridge](https://github.com/cncf/toc/issues/1546)
=> Remove archived projects from project and maintainers list

project-maintainers.csv
* [DevStream](https://github.com/cncf/toc/issues/1545)
* [OpenELB](https://github.com/cncf/toc/issues/1542)
=> Archive DevStream and OpenELB

project-maintainers.csv
See https://github.com/dapr/community/issues/593
=> Remove Mukundan Sundararajan as Dapr maintainer

project-maintainers.csv
Karmada PR: https://github.com/karmada-io/community/pull/138
=> add Karmada maintainer

project-maintainers.csv
=> chore: update projectcapsule meta and members associations

project-maintainers.csv
=> Update kpt maintainers

project-maintainers.csv
=> Add urunc maintainers

project-maintainers.csv
Added Maurice Ackel to OpenFGA
=> Update project-maintainers.csv for OpenFGA

project-maintainers.csv
=> Add Shao as Kubeflow Maintainer in CNCF Maintainer List.

policies-guidance/slack-backup.md
* Minor edits to text and formatting
=> Update some wording

project-maintainers.csv
=> Update the status of cri-o project and maintainers list

cncf-membership-guide.md, cncfgroups.md, journey-reports.md, policies-guidance/allowed-third-party-license-policy.md, policies-guidance/slack-guidelines.md, style-guide.md
We had some broken links due to folder reorganization. I ran lychee to find them. Also linted the Markdown on save.
=> Fix broken links flagged by lychee

project-maintainers.csv
refs:
https://github.com/oscal-compass/community/pull/138 (flowers)
https://github.com/oscal-compass/community/pull/139 (power)
=> Update OSCAL Compass projoect-maintainers: remove flowers & power

project-maintainers.csv
See https://github.com/cilium/cilium/pull/41284. CC @marseel
=> Update Cilium maintainers

project-maintainers.csv
related slack thread here:
- https://cloud-native.slack.com/archives/C08NY1D0NUQ/p1755185537599619?thread_ts=1755174449.432219&cid=C08NY1D0NUQ
=> chore: Add Andy Stoneberg as Kubeflow maintainer

project-maintainers.csv
=> Add parth-gr to rook maintainers

project-maintainers.csv
=> Remove myself from list of Vitess maintainers

project-maintainers.csv
Updating affiliations and removing member to reflect the membership according to https://github.com/open-telemetry/community/blob/main/community-members.md
=> Update project-maintainers.csv for OpenTelemetry

project-maintainers.csv
Affiliation changes for @mjudeikis
=> Update mjudeikis compnay
