style-guide.md
Simple fix in the reference of line number to the changelog
=> Fix changelog reference for kubectl pronunciation

code-of-conduct.md
The Kubernetes CoC docs all link back here, and I wanted to make sure that people know about the new k8s CoCC email address.
If this wording is okay, I'll try to replicate it on the translated pages as well.
=> Contact the K8s CoCC instead of Sarah going forward

whitelist-policy.md
This PR is to add the CNCF whitelist policy, which was adopted by the Governing Board on 2018-05-01 in connection with the CNCF IP policy.
cc @dankohn
Signed-off-by: Steve Winslow <swinslow@gmail.com>
=> Add CNCF whitelist policy

code-of-conduct-languages/es.md
During the https://github.com/kubernetes/website/pull/13543, @alexbrand spot a typo in the CNCF CoC Spanish version.
As stated in the README, the CNCF CoC can only be copied from the original, so we would like to fix the typo in the source to be able to update the website copy.
=> Fix typo in the Spanish CNCF CoC

code-of-conduct.md
This PR fixes the apostrophe in the sentence "Publishing other's private information...": as it is plural, it should be "others'".
=> Fixed apostrophe in others

README.md
fixing 404 link to point to a working link
OLD https://github.com/cncf/foundation/blob/master/copyright.md
NEW https://github.com/cncf/foundation/blob/master/copyright-notices.md
=> Updated copyright hyperlink

code-of-conduct-languages/pl.md, code-of-conduct.md
This translation of Code of Conduct is a part of Polish localization of Kubernetes documentation: https://github.com/kubernetes/website/pull/18419.
=> Add Polish translation of Code of Conduct

webinar-guidelines.md
For addition of Friday webinars for projects, SIGs, and Ambassadors
Clarity that end user supporters do not get a webinar.
=> Updating guidelines

blog-guidelines.md
Edits to content for clarification
Added details for distinguishing between member, project, ambassador, SIG, staff, and intern / event blogs.
=> Update blog guidelines

README.md
The third point in **Governance** where **membership** is highlighted links to an outdated link. When clicked, it shows:
It should link to "cncf-membership-agreement.pdf". Made the necessary changes.
=> Make changes to "membership agreement" in README.md

code-of-conduct.md
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Update CoC to reference conduct@cncf.io

code-of-conduct.md
Turkish translation is already available, but there is no reference for that in the code-of-conduct.md document.
=> Added Turkish to other languages available list in the code-of-conduct.md

project-maintainers.csv
Update the list of K3S maintainers as this has [changed recently](https://github.com/k3s-io/k3s/pull/3744/files).
Signed-off-by: David Nuzik <david.nuzik@rancher.com>
=> Update K3S maintainers

project-maintainers.csv
Synchronized the list of Jaeger maintainers with the information from the group @jaegertracing/jaeger-maintainers (https://github.com/orgs/jaegertracing/teams/jaeger-maintainers/members)
=> Update Jaeger maintainers

project-maintainers.csv
This PR adds Paul Mellor as a new maintainer of the Strimzi project into the `project-maintainers.csv` file.
=> Add Paul Mellor as new Strimzi project maintainer

project-maintainers.csv
As requested [here][link] I'm adding MetalLB as a Sandbox project.
Please note that Dax is not included as I'm not sure the company he is working on. Will do a follow-up PR later to include him.
cc @johananl @russellb @daxmc99
[link]: https://github.com/cncf/toc/issues/720#issue-996232534
=> Add MetalLB as Sandbox

project-maintainers.csv
As per https://github.com/chaos-mesh/chaos-mesh/pull/2298, this PR updated the maintainer list on the CNCF side.
=> Update Chaos Mesh maintainers

project-maintainers.csv
Signed-off-by: attleewang <attleewang@tencent.com>
Add sandbox project SuperEdge maintainers to project-maintainers file
=> Project-maintainers: Add sandbox project SuperEdge maintainers 

project-maintainers.csv
Adds myself, as per our maintainers list: https://github.com/kumahq/kuma/blob/master/OWNERS.md
Signed-off-by: austin ce <austin.cawley@gmail.com>
cc @idvoretskyi
=> Update kuma maintainers list

maintainers-election-policy.md
The CNCF GB met on Nov 1st 2021 and simplified the maintainer voting rules.
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Update maintainer voting rules per GB

project-maintainers.csv
Adding maintainers to SchemaHero project referenced from https://github.com/schemahero/schemahero/blob/main/OWNERS.md
=> updating maintainers list for SchemaHero

project-maintainers.csv
Signed-off-by: Mike Ng <ming@redhat.com>
Add sandbox project Open Cluster Management maintainers according to https://github.com/cncf/toc/issues/744
FYI @amye @qiujian16
=> Add Open Cluster Management maintainers

project-maintainers.csv
- maintainers(k8s): Update Kubernetes Steering Committee members 
Following the [2021 Kubernetes Steering Committee election](https://kubernetes.io/blog/2021/11/08/steering-committee-results-2021/), the
maintainers list should be updated to:
Add new Steering Committee members:
- @justaugustus
- @tpepper
Emeritus:
- @derekwaynecarr
@nikhita remains on the maintainers lists as a Kubernetes
SIG Contributor Experience lead.
- maintainers(k8s): List non-voting members w/ Service Desk access
Members of the following Special Interest Groups have access to
Service Desk:
- SIG Contributor Experience (@alisondy, @mrbobbytables, @cblecker, @nikhita)
- SIG Kubernetes Infra (@ameukam, @dims, @spiffxp, @thockin)
- SIG Release (@justaugustus, @saschagrunert, @cpanato, @jeremyrickard, @puerco)
Also, …
=> project-maintainers: Update Kubernetes maintainers list

project-maintainers.csv
Tom Kerkhove is now representing Microsoft, instead of Codit
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
=> docs: Tom Kerkhove is now representing Microsoft, instead of Codit

project-maintainers.csv
According to https://github.com/tikv/community/pull/158, TiKV Maintainer: Sun xiaoguang has joined PingCAP. 
So I update his company information in project-maintainers.csv
=> update tikv maintainer list in project-maintainers.csv

project-maintainers.csv
Federico Paolinelli was added as MetalLB maintainer here:
https://github.com/metallb/metallb/pull/993
Update this info here too.
cc @fedepaol 
Signed-off-by: Rodrigo Campos <rodrigo@kinvolk.io>
=> Add fedepaol as MetalLB maintainer

project-maintainers.csv
@amye we want to extend the maintainers list for OpenTelemetry to the TC members as well.
=> Add OpenTelemetry TC members to maintainers list

project-maintainers.csv
Bring into line with https://github.com/cortexproject/cortex/blob/1b7b74995b3e03f4bf351503372be9107c79bf76/MAINTAINERS.
Some people have moved company, some added, some removed.
Signed-off-by: Bryan Boreham <bjboreham@gmail.com>
CC @amye
=> Update Cortex maintainers

project-maintainers.csv
I'm an existing cert-manager maintainer and we're currently onboarding a new maintainer. This PR adds him to the official list - please also add him to any relevant CNCF mailing lists.
Thanks :grin:
=> Add Joakim Ahrlin (new cert-manager maintainer)

project-maintainers.csv
Updating Dapr Maintainers list to remove Mark Chmarny and add Abhilash Chandran
Signed-off-by: Mark Fussell <markfussell@gmail.com>
=> updating Dapr project maintainers

project-maintainers.csv
Adds @anvega and @amoore877 to spiffe maintainers who replaced Joe Beda and Emiliano Berenbaum in the SPIFFE SC as recorded on https://github.com/spiffe/spiffe/pull/207. 
Signed-off-by: Andres Vega <andresv@vmware.com>
=> Update spiffe maintainers

project-maintainers.csv
I was recently promoted to Keptn maintainers as a result of voting in https://github.com/keptn/community/issues/91. This pull request officially registers me as maintainer so that I can get access to the CNCF Support portal.
I also updated the maintainer list reference to https://github.com/keptn/keptn/blob/master/MAINTAINERS, because it is actual source of truth. As you may see there, there are many more maintainers that are currently not in the list. Once my account is registered as a maintainer in the CNCF, I will get it addressed. FTR https://github.com/keptn/community/issues/73 as a ticket on my side
=> Add @oleg-nenashev to the list of Keptn maintainers, update the maintainers link

project-maintainers.csv
- Updated Matt Farina to current company
- Removed Adnan from Helm as he has stepped down
- Removed community manager note on Karen as she is now
an org level maintainer
=> Updating project maintainers

project-maintainers.csv
Related to https://github.com/jaegertracing/jaeger/pull/3482
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
=> Remove jpkrohling from Jaeger

project-maintainers.csv
Hi @amye 
I recently became a maintainer of Falco, and I realized my name was missing in `project-maintainers.csv`. Is this the right way? Also, I think I may need to join the [cncf-falco-maintainers](https://lists.cncf.io/g/cncf-falco-maintainers) mailing list, can I have some guidance on how to do it? Thanks!
=> update(project-maintainers.csv): add jasondellaluce to Falco maintainers

project-maintainers.csv
Fix Longhorn project status. Longhorn is now a project in `Incubating`.
Signed-off-by: Sheng Yang <sheng@yasker.org>
=> Update project-maintainers.csv to fix Longhorn project status

project-maintainers.csv
Alkin has stepped down as maintainer.
Ref: https://github.com/vitessio/vitess/pull/9825
=> Remove askdba from Vitess maintainers

project-maintainers.csv
This adds the new "SIG Community" and "SIG Docs" maintainers (Orlin and Abigail) and also fixes Vadim's affiliation.
(I did not add @hainingzhang under "SIG Community" since he's already a project maintainer, but if he should be listed twice I'm happy to update.)
cc @Vad1mo @OrlinVasilev @a-mccarthy
=> Update Harbor maintainers (esp. Community+Docs)

project-maintainers.csv
Update to the KubeVirt maintainer's list:
- Remove Chris Calligari
- Add Andrew Burden
Signed-off-by: Stu Gott <stu-gott@users.noreply.github.com>
=> Update KubeVirt maintainers

project-maintainers.csv
Updates Tinkerbell maintainers:
* Updates Dan Finneran's affiliations (cc @thebsdbox).
* Adds Marques Johansson (myself, @displague).
* Adds Marky Jackson (@markyjackson-taulia)
Corresponding changes are being made in https://github.com/tinkerbell/org/pull/15
=> Update Tinkerbell maintainers list

project-maintainers.csv
Synchronizing kubevirt maintainer info.
xref https://github.com/kubevirt/community/pull/175
=> [kubevirt] Sync data of maintainer rmohr

project-maintainers.csv
Add initial maintainers for Confidential Containers Sandbox Project as per https://github.com/cncf/toc/issues/799
Signed-off-by: Tobin Feldman-Fitzthum <tobin@ibm.com>
=> Add Confidential Containers as Sandbox Project

project-maintainers.csv
Signed-off-by: Wiard van Rij <wvanrij@roku.com>
https://github.com/thanos-io/thanos/pull/5113
=> Adds Wiard van Rij as Thanos maintainer

project-maintainers.csv
Federico retired from his role as a KubeVirt maintainer. 
Merged KubeVirt Community PR: https://github.com/kubevirt/community/pull/176
=> Removing Federico Gimenez from the KubeVirt maintainers

project-maintainers.csv
Ref:
- fluxcd/go-git-providers#149
- fluxcd/flagger#1191
Full list of project maintainers here: https://github.com/fluxcd/community/blob/main/project/flux-project-maintainers.yaml
=> Flux: Remove Dinos Kousidis, add Sanskar Jaiswal

project-maintainers.csv
Aidan Delaney has been added to the buildpacks
leadership team. Reflect this in the CNCF project
maintainers document.
=> Add aidandelaney as Buildpacks maintainer

project-maintainers.csv
Brian Zhou and Raul Gracia are new Pravega maintainers
Andrei and Srikanth are at new organizations
=> Update maintainers for Pravega

project-maintainers.csv
@vinozzz recently was promoted to maintainer and this updates the CNCF record of who are maintainers for Porter to reflect that.
=> Add Yingrong Zhao as Porter maintainer

project-maintainers.csv
My employer does not define me as a computer scientist.
They are merely a vehicle to my retirement that stands in between my otherwise lifelong collaborative computer science work for the greater humanity and the united state's unique relationship with debt and worker exploitation.
Additionally my name was spelled wrong and that specific employer was very outdated. Please merge.
Signed-off-by: Kris Nóva <kris@nivenly.com>
=> Update Spelling / Employer

project-maintainers.csv
Hi there! This is an update to the Tinkerbell maintainers.
Removes Dan Finneran (cc, @thebsdbox).
Removes Marky Jackson (cc, @markyjackson-taulia).
Removes Manuel Mendez (cc, @mmlb).
Adds Jacob Weinstock (myself, @jacobweinstock).
Adds Jeremy Tanner (cc, @jeremytanner).
Adds Matt Anderson (cc, @matoszz).
Corresponding changes were made in tinkerbell/org#20
=> Update Tinkerbell maintainers

project-maintainers.csv
Hey @amye 
The last update of Falco governance precisely defines the [core maintainers' role](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#core-maintainers). They are responsible for overseeing the overall project's health and speaking on behalf of the project.
The core maintainers list is now published at :point_down:  
https://github.com/falcosecurity/evolution/blob/main/MAINTAINERS.md#core-maintainers
So, this PR updates in bulk the Falco core maintainers list in this repository.
We also kindly ask you to update the `cncf-falco-maintainers@lists.cncf.io` accordingly.
Thank you :pray: 
Leo
=> docs: bulk updates Falco maintainers

project-maintainers.csv
According to the recent change in https://github.com/chaos-mesh/chaos-mesh/pull/3512, we updated the list to add Zhiqiang Zhou (@STRRL) as a Chaos Mesh maintainer. 
Signed-off-by: Calvin Weng <wenghao@pingcap.com>
=> Update Chaos Mesh maintainer

project-maintainers.csv
* Add Yingrong Zhao, Brian DeGeeter and Steven Gettys to our maintainers
* Fix Vaughn's company association
* Update the repository path
=> Update Porter maintainers

project-maintainers.csv
Recently, OpenTelemetry Governance Committee has adopted a new project-level maintainer role of 'Community Maintainer'. This role is intended to act with the GC's blessing to support and maintain the project community of end-users and contributors. To this end, they require Service Desk access, and to receive project/event-related communications from the CNCF.
Please see https://github.com/open-telemetry/community/blob/main/governance-charter.md#community-manager-role for more information.
Signed-off-by: Austin Parker <austin@ap2.io>
=> Add Austin Parker

project-maintainers.csv
As of yesterday, Kured is a Sandbox project: https://lists.cncf.io/g/cncf-toc/message/7501
We will start on the move to a new GH org, etc in the next days.
cc @ckotzbauer @hiddeco @evrardjp @jackfrancis to please look over your details in this PR.
Signed-off-by: Daniel Holbach <daniel@holba.ch>
=> Add Kured as a Sandbox project

code-of-conduct.md
=> Fix typo in CNCF Community Code of Conduct v1.2

project-maintainers.csv
Without this, the github username doesn't reflect my name. This should fix it.
=> Fix typo in evrardjp fullname

project-maintainers.csv
Add OpenFGA Maintainers
For https://github.com/cncf/toc/issues/921
For https://github.com/openfga/community/issues/33
> Create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it
Signed-off-by: Andrés Aguiar <andres.aguiar@auth0.com>
=> Add OpenFGA Maintainers

project-maintainers.csv
This PR adds Lukas Kral and Maros Orsak as new maintainers for Strimzi.io project.
=> Strimzi: Add Lukas Kral and Maros Orsak to maintainers list

code-of-conduct-languages/tr.md
Updated Turkish version of Code of Conduct from v1.0 to v1.2 considering the latest version of English Code of Conduct file. (#375) 
Signed-off-by: Enes ahmedenesturan@gmail.com
=> Update Turkish Code of Conduct from v1.0 to v1.2

project-maintainers.csv
(Part of https://github.com/kubernetes/steering/issues/256.)
- Update Kubernetes Steering members
- Add:
- Benjamin Elder (@BenTheElder)
- Nabarun Pal (@palnabarun)
- Move to non-voting:
- Davanum Srinivas (@dims)
- Remove:
- Jordan Liggitt (@liggitt)
- Update Kubernetes non-voting members and affiliations
Signed-off-by: Stephen Augustus <foo@auggie.dev>
cc: @amye @caniszczyk
=> project-maintainers: Update Kubernetes maintainers list (2023)

project-maintainers.csv
Add maintainers who need service desk access while we start our transition and [seek clarity on who can be listed](https://github.com/cncf/foundation/issues/433).
Signed-off-by: craigbox <craigbox@google.com>
=> Add initial Istio maintainers

project-maintainers.csv
Signed-off-by: Matej Gera <38492574+matej-g@users.noreply.github.com>
Updating to reflect latest status (https://github.com/thanos-io/thanos/blob/main/MAINTAINERS.md).
=> Update Thanos project maintainers

project-maintainers.csv
Jaime has resigned his seat as an official NATS maintainer.
Signed-off-by: Ginger Collison <ginger@synadia.com>
=> Removing Jaime Piña from NATS Maintainer List

project-maintainers.csv
Cortex got a new maintainer. See https://github.com/cortexproject/cortex/pull/4959
Signed-off-by: Alvin Lin <alvinlin123@gmail.com>
=> Add new maintainer to Cortex project

project-maintainers.csv
Add Kemal Akkoyun to the Prometheus project
https://groups.google.com/g/prometheus-developers/c/8_20fF_r_VE
https://github.com/prometheus/docs/pull/2239
Signed-off-by: Kemal Akkoyun <kakkoyun@users.noreply.github.com>
=> Add Kemal Akkoyun to Prometheus project

project-maintainers.csv
This is a (late) update to the project maintainers based on the GC Election results.
https://opentelemetry.io/blog/2022/gc-election-results/
Related to: https://github.com/open-telemetry/community/issues/1169
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
=> Update OpenTelemetry with GC election results

project-maintainers.csv
Signed-off-by: Xavier Geerinck <xavier.geerinck@gmail.com>
Fixing a type of my name + updating the project I am working on
=> Fix typo of name in maintainers

project-maintainers.csv
Proposing to add Shubham Sharma whom is a very active contributor and official maintainer on Dapr
Signed-off-by: Xavier Geerinck <xavier.geerinck@gmail.com>
=> Add Shubham Sharma (Maintainer Dapr)

project-maintainers.csv
Adding myself to the Kubewarden maintainers list 
-> https://github.com/orgs/kubewarden/teams/maintainers/members
Signed-off-by: Olivier Vernin <olivier@vernin.me>
=> Add olivier vernin to Kubewarden Maintainers

project-maintainers.csv
Updates Thanos maintainers.
https://github.com/thanos-io/thanos/pull/5950
Signed-off-by: Saswata Mukherjee <saswataminsta@yahoo.com>
=> Add Filip and Saswata as Thanos maintainers

project-maintainers.csv
Signed-off-by: Chris Tarazi <chris@isovalent.com>
=> Add Tom Hadlaw to Cilium maintainers

project-maintainers.csv
This adds @adithyaj to Akri's Maintainers and updates company info for myself and @edrickwong 
Signed-off-by: Kate Goldenring <kate.goldenring@fermyon.com>
=> Add Adithya to Akri Maintainers

project-maintainers.csv
Add zot maintainers to CNCF project maintainers list as part of onboarding zot as a sandbox project.
Onboarding Issue: https://github.com/cncf/toc/issues/972
=> add zot maintainers

project-maintainers.csv
It seems that https://github.com/cncf/foundation/commit/ef8a83011c896f69e6c1ec2a5be3f62e77aabf36 removed my name from the list of Project Maintainers. Let's re-add so that I can submit our maintainer talk :)
Signed-off-by: gotjosh <josue.abreu@gmail.com>
=> Re-add Josh Abreu as a Prometheus Maintainer

project-maintainers.csv
Signed-off-by: Fabian Kramm <fab.kramm@googlemail.com>
=> Add DevSpace maintainers

project-maintainers.csv
This PR also removes @itsmurugappan from the maintainers list
Signed-off-by: salaboy <Salaboy@gmail.com>
=> Adding @puerco to Knative Projects maintainers

project-maintainers.csv
This PR updates the CSV to be consistent with the current [Kyverno maintainers list](https://github.com/kyverno/kyverno/blob/main/MAINTAINERS.md).
=> Update Kyverno active maintainers

project-maintainers.csv
ref: https://groups.google.com/a/kubernetes.io/g/dev/c/s-YJTRgbj9I/m/fs0_Xt9nBAAJ
ref: https://github.com/kubernetes/community/issues/7246
Added the new chairs and TLs to the list of K8s maintainers:
- Kaslin Fields
- Priyanka Saggu
- Madhav Jivrajani
This should be merged after https://github.com/kubernetes/community/pull/7247 is merged (this is merged now)
=> .: Add new SIG ContribEx Leads to K8s maintainers

project-maintainers.csv
We've added @diconico07 @johnsonshih and @yujinkim-msft as maintainers.
@yujinkim-msft is not a part of our codeowners but is essential to maintaining the Akri community, running [community meetings](https://hackmd.io/UUqW3_GgQDimQ5b23rS9rg), setting up and staffing our project pavilion booth at KubeCons, and maintaining Slack engagement.
=> Add new Akri maintainers

project-maintainers.csv
Alexander was approved today as an official maintainer to Keycloak https://github.com/keycloak/keycloak/blob/main/MAINTAINERS.md.
I would like to ask you to please include him to the list.
=> Add Alexander Schwartz to the list of maintainers

project-maintainers.csv
This PR updates the list of KubeVela maintainers, and changes the state of the project to Incubating. The current maintainer list can be found for reference in the [KubeVela community repo](https://github.com/kubevela/community/blob/main/OWNERS.md).
=> Update KubeVela maintainers

project-maintainers.csv
This PR updates the list of Xline maintainers. The current maintainer list can be found for reference in the [Xline community repo](https://github.com/datenlord/Xline/blob/master/MAINTAINERS).
=> Update Xline Maintainers

project-maintainers.csv
Reverts cncf/foundation#590
https://github.com/longhorn/longhorn/blob/master/MAINTAINERS does not match and they should.
=> Revert "Update longhorn maintainers"

charter.md
This section had different formatting than the surround text.
Signed-off-by: Brian Derr <bderrly@gmail.com>
=> Fix formatting of § 5.d.ii

code-of-conduct.md
fixes #602 
The link to Hindi code of conduct is not present on the English version unlike other localizations. This PR fixes it :)
=> Add link to `hi` code-of-conduct on `en` version

project-maintainers.csv
Byron Ruth voted in as a NATS maintainer by a majority vote of NATS maintainers [https://github.com/nats-io/nats-general/issues/90](url)
=> Add Byron Ruth to maintainers list

project-maintainers.csv
When we added Eraser as a Sandbox project, we missed the maintainers file. Adding it now.
=> docs: add maintainers file to Eraser entry

project-maintainers.csv
---
maintainers: Update Confidential Containers maintainers
Three new members have joined the Confidential Containers Steering
Committee (Ananya Garg and Vicent Batts, from Microsoft; Zvonko Kaiser,
from NVIDIA), and Intel has updated its representation (with Fabiano
Fidêncio replacing Dan Middleton).
---
project-maintainers: Update Confidential Containers URL
We've merged two repos into one, and now the list of the maintainers is
part of the governance file, which is now updated.
---
=> maintainers: Update Confidential Containers maintainers list & governance members URL

project-maintainers.csv
Update Maintainers list for the parsec project.
Signed-off-by: Tomás González <tomasagustin.gonzalezorlando@arm.com>
=> parsec: Update Maintainers list

license-exceptions/cncf-exceptions-2021-07-19.json
Create cncf-exceptions-2021-07-19.json, missed this in the last round
=> Adding .json for license exceptions

project-maintainers.csv
- Update Kubernetes Steering members for 2023 election
- Add:
- Maciej Szulik - @soltysh
- Paco Xu 徐俊杰 - @pacoxu
- Patrick Ohly - @pohly
- Emeritus Steering:
- Carlos Tadeu Panato Jr. - @cpanato (remains on the list as a SIG Release Technical Lead)
- Christoph Blecker - @cblecker (remains on the list as a SIG Contributor Experience Technical Lead)
- Tim Pepper - @tpepper
- Add Verónica López (@Verolop) to SIG Release leads
Thanks to all of the Emeritus members for your service and welcome to the new Kubernetes Steering Committee members!
Signed-off-by: Stephen Augustus <foo@auggie.dev>
cc: @amye @caniszczyk @mrbobbytables @BenTheElder @palnabarun 
xref: https://github.com/kubernetes/steering/issues/273
=> project_maintainers: Update Kubernetes memberships

copyright-notices.md, license-notices.md
This PR adds a couple of internal links between CNCF guidance documents.
=> Add links to attribution recommendations

project-maintainers.csv
This is adding kcp maintainers (after we have elected a couple of new maintainers through our project governance process).
Towards https://github.com/cncf/toc/issues/1173
=> Add maintainers for kcp in CNCF Sandbox

project-maintainers.csv
This PR updates the maintainers list of external-secrets. Going to update via [cncf-maintainer-changes@cncf.io](mailto:cncf-maintainer-changes@cncf.io) as well as described in the readme.
=> feat: update project maintainers

project-maintainers.csv
Removed community maintainer since @austinlparker is now listed above under GC.
Updated technical committee members:
* added @bogdandrutu and @yurishkuro who were previously under GC
* added @reyang and @jack-berg who were not listed yet
* removed @SergeyKanzhelev who is emeritus now
=> Update OpenTelemetry project maintainers

project-maintainers.csv
Recently SIG etcd was established, with two tech leads and chair roles.
As discussed and agreed through maintainer majority in https://github.com/etcd-io/etcd/pull/16794#issuecomment-1783987851 this pull request:
1. Renames the etcd project maintainers source of truth to our newly added `OWNERS` file.
2. Adds a separate section under etcd for SIG etcd leadership roles .
cc @serathius, @ahrtr, @wenjiaswe, @jberkus
=> Add SIG etcd leadership roles

code-of-conduct.md
1. Fix typos for `occcuring` words
2. There are tones of unnecessary trailing spaces in the file, removed them
3. Use unified link for email addresses
=> Tweak and improve code of conduct documentation

project-maintainers.csv
Adding Piotr Piotrowski to NATS maintainers via majority vote [Issue #93]( https://github.com/nats-io/nats-general/issues/93)
=> Add Piotr Piotrowski to NATS Maintainers

project-maintainers.csv
Updating Knative project maintainers after Steering Committee Elections.
References:
- https://github.com/knative/community/issues/1468
- https://github.com/knative/community/pull/1469
- https://github.com/knative/community/pull/1395
- https://github.com/knative/community/tree/main/peribolos
=> Update Knative project maintainers

project-maintainers.csv
This brings project-maintainers.csv in line with
https://github.com/crossplane/crossplane/blob/master/OWNERS.md
=> Update project-maintainers.csv for crossplane

project-maintainers.csv
This is a quick follow up PR to #680 to correct a typo in the GitHub user name for https://github.com/phisco.
=> Fix typo for phisco in project-maintainers.csv for Crossplane

project-maintainers.csv
this change updates the company info for the existing trickster maintainers, and adds @jnichols-git to the maintainers list.
=> update trickster maintainers

project-maintainers.csv
Spiderpool is recently proved to be a sandbox project, this PR adds its maintainers
context:
https://github.com/cncf/toc/issues/1225
https://github.com/cncf/sandbox/issues/33
=> add new maintainer for Spiderpool

project-maintainers.csv
Cecil is a new community manager for Dapr. Nyemade has left the project. 
See https://github.com/dapr/community/issues/430
=> Add Cecil Phillip, remove Nyemade Uverski

project-maintainers.csv
Please add Arko Dasgupta, Huabing Zhao and Jianpeng He to the list of maintainers of envoyproxy/gateway as per https://github.com/envoyproxy/gateway/graphs/contributors
=> Add maintainers for Envoy Gateway project

project-maintainers.csv
Add Troy Connor to list of maintainers of `getporter/porter` as per https://github.com/orgs/getporter/teams/maintainers
=> Add troy0820 to list of maintainers for porter

project-maintainers.csv
As we decided in Knative community, we want to have the WG leads in the maintainers list: https://github.com/knative/community/issues/1383#issuecomment-1865809475
Added missing people from the list https://github.com/knative/community/blob/main/peribolos/knative-OWNERS_ALIASES
cc @puerco @salaboy @nainaz @evankanderson
=> AddKnative  WG leads to maintainers list

code-of-conduct-languages/cs.md
Updating Czech translation.
Deploy preview: https://github.com/nate-double-u/cncf-foundation/blob/2024-02-09-NW-code-of-conduct-translation-update-Czech/code-of-conduct-languages/cs.md
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206550547415097
- https://app.asana.com/0/0/1206616792109812
=> Updating code of conduct Czech translation

code-of-conduct-languages/id.md
Updating Indonesian translation.
Deploy preview: https://github.com/nate-double-u/cncf-foundation/blob/2024-02-16-NW-code-of-conduct-translation-update-Indonesian/code-of-conduct-languages/id.md
=> Updating code of conduct translation: Indonesian

style-guide.md
Include "KEDA" in preferred capitalization to ensure that new press releases respect it, although https://www.cncf.io/projects/keda/ already has it correct
=> docs: Include "KEDA" in preferred capitalization

code-of-conduct-languages/fr.md
Updating French translation.
Deploy preview: https://github.com/nate-double-u/cncf-foundation/blob/2024-03-25-NW-code-of-conduct-translation-update-French/code-of-conduct-languages/fr.md
=> Updating code of conduct translation: French

code-of-conduct-languages/de.md
Updating German translation.
Deploy preview: https://github.com/nate-double-u/cncf-foundation/blob/2024-03-25-NW-code-of-conduct-translation-update-German/code-of-conduct-languages/de.md
=> Updating code of conduct translation: German

code-of-conduct-languages/it.md
Updating Italian translation.
Deploy preview: https://github.com/nate-double-u/cncf-foundation/blob/2024-03-25-NW-code-of-conduct-translation-update-Italian/code-of-conduct-languages/it.md
=> Updating code of conduct translation: Italian

code-of-conduct-languages/pl.md
Updating Polish translation.
Deploy preview: https://github.com/nate-double-u/cncf-foundation/blob/2024-03-26-NW-code-of-conduct-translation-update-Polish/code-of-conduct-languages/pl.md
=> Updating code of conduct translation: Polish

code-of-conduct-languages/tr.md
Updating Turkish translation.
Deploy preview: https://github.com/nate-double-u/cncf-foundation/blob/2024-04-09-NW-code-of-conduct-translation-update-Turkish/code-of-conduct-languages/tr.md
=> Updating code of conduct translation: Turkish

project-maintainers.csv
Kubean is recently proved to be a sandbox project, this PR adds its maintainers
context:
https://github.com/cncf/toc/issues/1301
https://github.com/cncf/sandbox/issues/49
=> add new maintainer for Kubean

project-maintainers.csv
* Update @darach and @Licenser assocation to Axiom Inc ( axiom.co )
* Update @mfelsche association to GSMK Gmbh
* Add missing @natalisucks entry to project maintainers as it was missing
* Remove @anupdhml from project tremor maintainers
* Update @skoech now works at Canonical
=> Update tremor project maintainer and associations

project-maintainers.csv
Here the link of falco core maintainers:
https://github.com/falcosecurity/evolution/blob/main/MAINTAINERS.md#core-maintainers
Can you also add me to cncf-falco-maintainers@lists.cncf.io mailing list, please?
=> add alacuku to Falco maintainers

code-of-conduct-languages/es.md
Updating Spanish translation.
Deploy preview: https://github.com/nate-double-u/cncf-foundation/blob/2024-04-09-NW-code-of-conduct-translation-update-Spanish/code-of-conduct-languages/es.md
=> Updating code of conduct translation: Spanish

code-of-conduct-languages/vi.md
Updating Vietnamese translation.
Deploy preview: https://github.com/nate-double-u/cncf-foundation/blob/2024-04-09-NW-code-of-conduct-translation-update-Vietnamese/code-of-conduct-languages/vi.md
=> Updating code of conduct translation: Vietnamese

project-maintainers.csv
Add new maintainers (Chinya, Eric) to Longhorn. They are already added to the maintainer list of the Longhorn repo at https://github.com/longhorn/longhorn/blob/master/MAINTAINERS#L9-L10
=> Update longhorn maintainers

project-maintainers.csv
Adam was accepted as a maintainer in https://github.com/cert-manager/community/pull/23. I propose to add him to here.
=> project-maintainers: add Adam Talbot as maintainer of cert-manager

project-maintainers.csv
Adding myself, Anton Gilgur, @agilgur5 to the `project-maintainers.csv` file to have access to CNCF Support Desk etc.
Also emailed cncf-maintainer-changes@cncf.io according to [the README](https://github.com/cncf/foundation/blob/a6649a1fd125243fb134d2d3fc98367384ed28be/README.md?plain=1#L28), referencing this PR and using the same email as in my DCO in the commit here
Source:
- Argoproj: https://github.com/argoproj/argoproj/blob/e9828ebaa8e23e6ed21d05aa7ee74556383c41be/MAINTAINERS.md?plain=1#L32
- Reviewer: https://github.com/argoproj/argoproj/pull/257, https://github.com/argoproj/argoproj/issues/242 
- Approver: https://github.com/argoproj/argoproj/pull/280, https://github.com/argoproj/argoproj/issues/277
- Argo Workflows: https://github.com/argoproj/argo-workflows/blob/74b034c9d1e5315c36 …
=> Add Anton Gilgur (agilgur5) to Argo Maintainers

project-maintainers.csv
This PR updates the maintainers list and also updates the link which points to the up to date maintainers list in the project.
=> Update metal3-io maintainer list

project-maintainers.csv
This is related to the task list attached to https://github.com/cncf/toc/issues/1374.
The 4 of us are the core regular maintainers at this time for anything under https://github.com/score-spec.
Please let me know if there are any questions.
=> Added: Score sandbox project maintainers

project-maintainers.csv
This PR does two things:
- Update the status of the Falco project to match the current situation (Incubating -> Graduated)
- Update the maintainers list to add myself
The graduation announcement can be found [here](https://www.cncf.io/announcements/2024/02/29/cloud-native-computing-foundation-announces-falco-graduation/).
=> feat(falco): update status and maintainers

project-maintainers.csv
This PR updates the level of the Strimzi project in the project maintainers list from Sandbox to Incubating as Strimzi moved to Incubating earlier this year. It also updates the company affiliation for Stanislav Knot - one of the Strimzi maintainers.
=> Update the Strimzi level to Incubating

project-maintainers.csv
Add OSCAL-COMPASS maintainers to `project-maintainer.csv`. 
Related to https://github.com/cncf/toc/issues/1371
=> Add OSCAL-COMPASS maintainers

project-maintainers.csv
As described here: https://github.com/cert-manager/community/pull/32#issuecomment-2285854108
Erik is a newly accepted cert-manager maintainer and should be in the `project-maintainers.csv` file.
@erikgb FYI
=> Add Erik Godding Boye as a cert-manager maintainer

code-of-conduct.md
This pull request amends the scope of the code of conduct applicability when words or actions are directed at another CNCF community member to add:
> in the context of a CNCF activity
=> Add specificity to the scope of CoC applicability

project-maintainers.csv
Martin has stepped down from the role. You can see it at https://lists.cncf.io/g/cncf-helm/topic/stepping_down_as_helm/107404058
=> Removing Martin as a Helm maintainer

project-maintainers.csv
This does a couple things:
1. Remove Matt Fisher and Adam Reese as maintainers. If you look at the maintainers you can see then removed themselves. See https://github.com/helm/community/blob/main/MAINTAINERS.md
2. Updated the employment for several members who have changed jobs since the last update.
=> Updating Helm maintainers

project-maintainers.csv
The wasmCloud maintainers had not been updated properly here. This adds myself as a starting point and points the link to maintainers to the correct location. You can check that list to verify that I am a maintainer
=> chore(maintainers): Add myself as a wasmCloud maintainer

project-maintainers.csv
Most of the maintainers were unaware this file existed! We've fixed this in our onboarding documents, but this PR updates the list of wasmCloud org maintainers to match the current org maintainers for wasmCloud.
This can be double checked in the linked MAINTAINERS.md file for verification
=> chore(project-maintainers): Reconciles wasmCloud project maintainers

project-maintainers.csv
Congratulations to the elected committee members whose two year terms begin immediately (listed in alphabetical order by GitHub handle):
- Antonio Ojea ([@aojea](https://github.com/aojea)), Google
- Benjamin Elder ([@BenTheElder](https://github.com/bentheelder)), Google
- Sascha Grunert ([@saschagrunert](https://github.com/saschagrunert)), Red Hat
They join continuing members:
- Stephen Augustus ([@justaugustus](https://github.com/justaugustus)), Cisco
- Paco Xu 徐俊杰 ([@pacoxu](https://github.com/pacoxu)), DaoCloud
- Patrick Ohly ([@pohly](https://github.com/pohly)), Intel
- Maciej Szulik ([@soltysh](https://github.com/soltysh)), Defense Unicorns
- Benjamin Elder is a returning Steering Committee Member.
Thanks to the Emeritus Steering Committee Members. Your service is appreciated by the …
=> Update Kubernetes steering members for 2024 election

project-maintainers.csv
As of the 2024 election results published in https://vote.heliosvoting.org/helios/e/otel-gc-2024 to match the list in https://github.com/open-telemetry/community/blob/main/community-members.md#governance-committee
=> Update OpenTelemetry Governance Committee members

project-maintainers.csv
Removing myself, `agilgur5`, from Argo maintainers as I resigned
Source:
- Argoproj: https://github.com/argoproj/argoproj/pull/336
- Argo Workflows: https://github.com/argoproj/argo-workflows/pull/13837
Effectively the inverse of #800
=> Remove `agilgur5` from Argo maintainers

project-maintainers.csv
Adding lmolkova (Liudmila Molkova) to reflect her membership in the OpenTelemetry Technical Committee.
=> Add lmolkova to project-maintainers.csv

project-maintainers.csv
Hi, 
Please review and accept the enclosed updates to the list of Kuma maintainers.
The reference tracking information is here: https://github.com/kumahq/kuma/pull/12091
Thanks
=> Add kuma project maintainers

project-maintainers.csv
I added @akgraner to the Kubeflow Maintainers since she is leading the Kubeflow Outreach committee.
cc @johnugeorge @jbottum @terrytangyuan @james-jwu
=> Add akgraner to Kubeflow Maintainers

allowed-third-party-license-policy.md
The Legal Committee recommended adding the following licenses to the Allowlist and the Governing Board approved on September 26, 2024.
- 0BSD
- MIT-0
- OpenSSL
- OpenSSL-standalone
- SSLeay-standalone
- UPL-1.0
=> Add licenses that were approved by the GB on Sep 26.

project-maintainers.csv
This PR adds Kate Stanley (katheris) as a new maintainer of the Strimzi project into the project-maintainers.csv file.
=> Add Kate Stanley as a new Strimzi project maintainer

.github/pull_request_template.md
There are several tasks that should be done when a maintainer is added, updated, or removed.
Eventually this process will be automated and be self-serve, but for now we need to make sure each step is followed to ensure consistency.
=> Add checklist to remind of additional maintainer management tasks.

project-maintainers.csv
Was doing some housekeeping on our email list and realized that wasmCloud's status hadn't been updated to Incubating yet
=> chore(maintainers): Updates wasmCloud to incubating

project-maintainers.csv
- remove duplicate name of `Xunzhuo Liu` (disappeared in L71)
- remove `Alice Wasko` from Envoy Gateway maintainers
- add `Xiaohan Hu` as a Envoy Gateway maintainer
cc @arkodg
=> Update Envoy Gateway maintainer status

project-maintainers.csv
- Replaces @azdagron with @sorindumitru.
- Update company affiliations.
Ref: https://github.com/spiffe/spire/pull/5827
=> Update SPIRE maintainers

project-maintainers.csv
Removing Andrew Mason from Vitess. See https://github.com/vitessio/vitess/pull/17745
=> Update Vitess maintainers

.github/workflows/validate-csv.yml
=> Action to validate changes to maintainers.

project-maintainers.csv
👋 I am a maintainer of the [Devfile Sanbox project](https://devfile.io) since day one (c.f. the [maintainers file](https://github.com/devfile/api/blob/main/MAINTAINERS.md)) but for some reason I am not included in the `project-maintainers.csv` file.
=> Updating devfile maintainers

project-maintainers.csv
Our subprojects have separate maintainers, so while the majority of this is sourced from [Podman's maintainer list](https://github.com/containers/podman/blob/main/MAINTAINERS.md) there are also a few maintainers from [Skopeo](https://github.com/containers/skopeo/blob/main/MAINTAINERS.md) and [Buildah](https://github.com/containers/buildah/blob/main/MAINTAINERS.md) not in that file.
=> Add Podman Container Tools to project-maintainers.csv

project-maintainers.csv
As a [maintainer for Keycloak](https://github.com/keycloak/keycloak/blob/main/MAINTAINERS.md?plain=1#L12), synching my affiliation with the CNCF Maintainers file.
=> Update Keycloak Project Maintainer affiliation for thomasdarimont

project-maintainers.csv
=> Add Dipti Pai to Flux maintainers

project-maintainers.csv
Updating KubeVirt maintainers list as two of our maintainers recently stepped down:
Vasiliy: https://github.com/kubevirt/community/pull/396
Alice: https://github.com/kubevirt/community/pull/406
=> Removing Vasiliy and Alice as KubeVirt maintainers

project-maintainers.csv
I have been a maintainer for the Fluent project for a while now, primarily though around Fluent Bit, so catching up on related CNCF access.
=> update(project-maintainers.csv): add patrick-stephens as Fluent maintainer

policies-guidance/website-guidelines.md
* Updated to reflect the latest format used in the 2025 Contribution Agreement instructions.
* Fixed link back to copyright guidance doc.
=> Add latest copyright/trademark footer format

project-maintainers.csv
Added Mike Azure as a maintainer for Drasi
=> Update project-maintainers.csv to add new maintainer for Drasi

project-maintainers.csv
This pull request updates the `project-maintainers.csv` file to add new maintainers for the "Incubating, Flatcar Container Linux" project.
* Added Jan Bronicki (`John15321`), Daniel Zaťovič (`danzatt`), and Ervin Rácz (`ervcz`) as maintainers from Microsoft.
=> Add new Flatcar maintainers

project-maintainers.csv
I want to add myself as an official maintainer of OpenFeature:
- the org config: https://github.com/open-feature/community/blob/7a248734bf23893b84c0c9c123a332ba65589f1e/config/open-feature/org.yaml#L179-L181
- the promotion pr: https://github.com/open-feature/community/pull/438
- the official maintainer team in the org: https://github.com/orgs/open-feature/teams/maintainers
=> Add Simon Schrottner <aepfli> to the maintainers of open-feature

.github/workflows/validate-csv.yml
today (before this PR):
leads to the following typo in ci/GHA display name
with this PR:
fix typo s/cvs/csv/
=> ci: fix typo in Job name

project-maintainers.csv
KAITO CODEOWNERS: https://github.com/kaito-project/kaito/blob/main/CODEOWNERS
=> Add chewong and zhuangqh to KAITO maintainer list

project-maintainers.csv
Updating my affiliation from Cisco -> Causely
=> Update affiliation for svrnm in OTel Maintainers

project-maintainers.csv
Add [kserve maintainers](https://github.com/kserve/kserve/blob/master/OWNERS) to CNCF project maintainers list as part of the onboarding https://github.com/cncf/toc/issues/1905.
=> Add kserve maintainers to the project maintainers list

project-maintainers.csv
- https://github.com/kube-logging/logging-operator/pull/2107
=> update logging-operator maintainers
